/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_tMWcqKcfM",
    "aws_user_pools_web_client_id": "8rkt1paa8hbm89v6bfabvrc1e",
    "oauth": {}
};


export default awsmobile;
